/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.tez.runtime.api.events;

import com.google.protobuf.ByteString;
import org.apache.tez.runtime.api.Event;

/**
 * Event generated by an Input to indicate error when trying to retrieve data.
 * This is not necessarily a fatal event - it's an indication to the AM to retry
 * source data generation.
 */
public final class DAGOutputEvent extends Event {

  private final String resultId;
  private final ByteString dagOutput;
  private final int numRows;

  private DAGOutputEvent(String resultId, ByteString dagOutput, int numRows) {
    super();
    this.resultId = resultId;
    this.dagOutput = dagOutput;
    this.numRows = numRows;
  }

  public static DAGOutputEvent create(String resultId, ByteString dagOutput, int numRows) {
    return new DAGOutputEvent(resultId, dagOutput, numRows);
  }

  public String getResultId() {
    return resultId;
  }

  public ByteString getDagOutput() {
    return dagOutput;
  }

  public int getNumRows() {
    return numRows;
  }
}
